const assert=require('node:assert/strict');require('../dist/engine.js');require('../dist/solver.js');
const A=Advisor,D=DC,ids=names=>names.map(name=>D.heroes.find(hero=>hero.localized_name===name).id),own=ids(['Muerta','Mirana','Mars','Hoodwink','Lion']),enemy=ids(['Chaos Knight','Batrider','Centaur Warrunner','Vengeful Spirit','Rubick']),state={own,enemy,bans:[],roles:Object.fromEntries(own.map((id,i)=>[id,A.roles[i]])),enemyRoles:{},side:'radiant'};
const baseline=A.defaultBuilds(state),before=JSON.stringify(baseline),candidates=Array.from(A.itemCandidates(state,baseline));assert(candidates.length>1000);assert.equal(JSON.stringify(baseline),before);
for(const candidate of candidates){assert.equal(Object.keys(candidate).length,5);assert.equal(Object.keys(candidate).filter(id=>JSON.stringify(candidate[id])!==JSON.stringify(baseline[id])).length,1);for(const build of Object.values(candidate)){assert.equal(build.length,6);assert.equal(new Set(build).size,6);assert.deepEqual(D.builds.c6(build),build);assert(build.every(id=>D.items.some(item=>item.id===id&&!item.retired)))}}
let current=baseline;const live=A.itemCandidates(state,()=>current),first=live.next().value;current=first;const changedId=Object.keys(first).find(id=>JSON.stringify(first[id])!==JSON.stringify(baseline[id]));let other;while(!(other=live.next()).done){if(JSON.stringify(other.value[changedId])===JSON.stringify(first[changedId]))break}assert(!other.done,'later candidates keep accepted changes for other heroes');
const native=D.simulate;let payload;D.simulate=input=>{payload=input;return{winner:'radiant',finalMinute:30,timeline:[{totals:{radiantNetWorth:10000,direNetWorth:9000}}]}};
A.simulate(state,D.presets.lateScale,D.presets.earlyAggro,'radiant',first);assert.deepEqual(payload.playerItemBuilds,first);assert.deepEqual(payload.enemyItemBuilds,Object.fromEntries(enemy.map(id=>[id,D.builds.z8(id,A.assigned(enemy)[id])])));D.simulate=native;
console.log('Verified legal ordered item candidates, retired-item exclusion, preserved accepted team changes, and explicit native simulation payloads.');

(async()=>{const fs=require('node:fs'),vm=require('node:vm'),source=fs.readFileSync('rebuild/overlay.js','utf8'),fn=source.slice(source.indexOf(' async function autoStep('),source.indexOf(' // Keep movement'));let calls=0;const nodes={},context={auto:true,autoBusy:false,autoPhase:'items',autoIndex:0,autoRoles:state.roles,autoItems:baseline,state,document:{},DC:D,Advisor:A,JSON,Date,$:id=>nodes[id]||(nodes[id]={}),readDraftSnapshot:()=>({completed:{radiant:own},roles:state.roles}),stopAuto:message=>{throw Error(message)},AdvisorGame:{prepStatus:()=>null,setItem:()=>{calls++;return 'verified'}}};vm.createContext(context);vm.runInContext(fn+';this.step=autoStep;',context);await context.step();assert.equal(calls,30);assert.equal(context.autoPhase,'apply');assert.equal(context.autoIndex,0);context.autoPhase='items';calls=0;context.AdvisorGame.setItem=()=>{calls++;return 'opened'};await context.step();assert.equal(calls,1);assert.equal(context.autoIndex,0);assert.equal(context.autoPhase,'items');console.log('Verified unchanged item slots advance in one read pass, while each item-picker mutation yields before the next action.');})().catch(error=>{console.error(error);process.exitCode=1});
