const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
require('../dist/engine.js');require('../dist/solver.js');
const A=Advisor,D=DC,id=name=>D.heroes.find(h=>h.localized_name===name).id;
const state={own:['Slark','Queen of Pain','Enigma','Earthshaker','Hoodwink'].map(id),enemy:['Chaos Knight','Kunkka','Timbersaw','Vengeful Spirit','Disruptor'].map(id),bans:[],roles:{},enemyRoles:{},side:'dire'};
const original=JSON.stringify(state),variants=Array.from(A.opponentVariants(state));assert(variants.length>=76);assert.equal(JSON.stringify(state),original);
const base=variants[0];for(const variant of variants){assert.equal(new Set(Object.values(variant.roles)).size,5);for(const hero of state.enemy){assert(variant.items[hero].length===6);assert.equal(new Set(variant.items[hero]).size,6);assert.deepEqual(D.builds.c6(variant.items[hero]),variant.items[hero]);if(variant.roles[hero]!==base.roles[hero])assert(D.roles.aQ(A.byId.get(hero),variant.roles[hero]))}}
const fixed={...state,enemyRoles:base.roles};assert(Array.from(A.opponentVariants(fixed)).every(v=>JSON.stringify(v.roles)===JSON.stringify(base.roles)));
const native=D.simulate;let payload;D.simulate=input=>{payload=input;return{winner:'dire',finalMinute:30,timeline:[{totals:{radiantNetWorth:1000,direNetWorth:2000}}]}};
A.simulate(state,D.presets.lateScale,D.presets.earlyAggro,'dire',A.defaultBuilds(state),variants.at(-1));assert.deepEqual(payload.enemyStrategyHeroRoles,variants.at(-1).roles);assert.deepEqual(payload.enemyItemBuilds,variants.at(-1).items);D.simulate=native;
const source=fs.readFileSync('rebuild/overlay.js','utf8'),fn=source.slice(source.indexOf(' async function checkSensitivity('),source.indexOf(' async function optimize('));
async function check(limitStep=0,cancel=false){let time=0,calls=0;const nodes={},context={auto:false,state:{own:[1,2,3,4,5],enemy:[6,7,8,9,10]},token:0,analysisMode:'fast',config:{choices:{id:1},itemBuilds:{id:'selected'}},choices:{},sensitivity:null,JSON,Promise,Date:{now:()=>time},setTimeout:callback=>{if(cancel)context.token++;callback()},$:id=>nodes[id]||(nodes[id]={}),renderContent:()=>{},Advisor:{defaultBuilds:()=>({id:'default'}),scenarios:()=>({enemyPlans:[{}],sides:['dire']}),opponentVariants:function*(){yield{label:'base'};yield{label:'swap'}},simulate:(state,plan,enemy,side,builds)=>{calls++;time+=limitStep;return{win:builds.id==='selected',nw:builds.id==='selected'?100:-100}}}};vm.createContext(context);vm.runInContext(fn+';this.run=checkSensitivity;',context);await context.run();return{context,calls}}
(async()=>{const complete=await check();assert.equal(complete.context.sensitivity.completed,2);assert.equal(complete.context.sensitivity.selectedWins,2);assert.equal(complete.context.sensitivity.defaultWins,0);assert.equal(complete.context.config.itemBuilds.id,'selected');const partial=await check(6000);assert.equal(partial.context.sensitivity.completed,0);assert.equal(partial.calls,2);const cancelled=await check(0,true);assert.equal(cancelled.calls,0);assert.equal(cancelled.context.sensitivity,null);console.log('Verified native-eligible opponent variants, known role locks, explicit simulation inputs, matched baseline comparisons, incomplete-pair exclusion, cancellation and unchanged recommendations.');})().catch(error=>{console.error(error);process.exitCode=1});
