// Finite win-payoff zero-sum game. Solve the positive shifted column-player LP.
function solve(payoff){const m=payoff.length,n=payoff[0]?.length;if(!m||!n||payoff.some(row=>row.length!==n||row.some(v=>!Number.isFinite(v)||v<0||v>1)))throw Error('Expected a rectangular payoff matrix in [0,1]');
 const rhs=n+m,table=payoff.map((row,i)=>[...row.map(v=>v+1),...Array.from({length:m},(_,j)=>Number(i===j)),1]),basis=Array.from({length:m},(_,i)=>n+i),objective=[...Array(n).fill(-1),...Array(m).fill(0),0],eps=1e-10;table.push(objective);let pivots=0;
 for(;;){const entering=objective.slice(0,rhs).findIndex(v=>v<-eps);if(entering<0)break;let leaving=-1,ratio=Infinity;for(let i=0;i<m;i++){const a=table[i][entering];if(a<=eps)continue;const r=table[i][rhs]/a;if(r<ratio-eps||Math.abs(r-ratio)<=eps&&(leaving<0||basis[i]<basis[leaving])){ratio=r;leaving=i}}if(leaving<0)throw Error('Unbounded shifted game LP');const pivot=table[leaving][entering];for(let j=0;j<=rhs;j++)table[leaving][j]/=pivot;for(let i=0;i<=m;i++){if(i===leaving)continue;const factor=table[i][entering];for(let j=0;j<=rhs;j++)table[i][j]-=factor*table[leaving][j]}basis[leaving]=entering;pivots++;
 }
 const x=Array(n).fill(0);for(let i=0;i<m;i++)if(basis[i]<n)x[basis[i]]=table[i][rhs];const normalize=weights=>{const cleaned=weights.map(v=>Math.max(0,v)),sum=cleaned.reduce((a,b)=>a+b,0);if(!sum||!Number.isFinite(sum))throw Error('Invalid LP distribution');return cleaned.map(v=>v/sum)},row=normalize(objective.slice(n,rhs)),column=normalize(x),columnReturns=Array.from({length:n},(_,j)=>payoff.reduce((s,r,i)=>s+row[i]*r[j],0)),rowReturns=payoff.map(r=>r.reduce((s,v,j)=>s+v*column[j],0)),lower=Math.min(...columnReturns),upper=Math.max(...rowReturns),gap=upper-lower;
 if(!Number.isFinite(gap)||gap>1e-7)throw Error('Uncertified minimax solution');return{row,column,lower,upper,gap,pivots,worstColumn:columnReturns.indexOf(lower),bestRow:rowReturns.indexOf(upper)};
}
function sample(weights,rng=Math.random){const mass=weights.reduce((s,w)=>s+w,0);if(!mass||weights.some(w=>!Number.isFinite(w)||w<0))throw Error('Invalid strategy weights');const u=rng();if(u<0||u>=1||!Number.isFinite(u))throw Error('Expected uniform draw in [0,1)');let draw=u*mass,last=-1;for(let i=0;i<weights.length;i++){if(weights[i]>0)last=i;draw-=weights[i];if(draw<0)return i}return last}
module.exports={solve,sample};
